### ISSUE TITLE
Support `Deno.dlopen` for bundling libraries

### ISSUE THREAD

**Issue by mwcz** [mandarineorg/leaf#21]
This is somewhat related to #19, but I opened a separate issue because [`dlopen`](https://doc.deno.land/deno/unstable@v1.17.1/~/Deno.dlopen) seems uniquely different from other filesystem reads.  This would be make it possible to use leaf to bundle, a Rust library, for example, in a single executable.

**Comment by clemens-tolboom** [comment]
Testing the CLI
```zsh
Deno --unstable
> Deno.dlopen
[Function: dlopen]
```

Leaf uses [`const fileContent = Deno.readFileSync(filePath);`](https://github.com/mandarineorg/leaf/blob/main/leafCompiler.ts#L70) and overrides it.

Can you provide a typescript example opening and serving out from a Deno.readFileSync + (magic?) + Deno.dlopen using a public DLL?

**Comment by mwcz** [comment]
Consensus in discord is that this request isn't possible because dlopen is provided by the OS, so it can't be overridden in leaf.

**Comment by clemens-tolboom** [comment]
Where did that discussion took place? Do you have a link to Discord discussion? I spend some time writing so useful feedback would help :-)

**Comment by mwcz** [comment]
Sure, here's the conversation. I'm not sure how to link to discord messages, but here's some screenshots.

![markup_23931](https://user-images.githubusercontent.com/364615/158440501-a95a72da-affd-4a25-864a-083b4a7cc37b.png)
![markup_23934](https://user-images.githubusercontent.com/364615/158440504-580aadf5-bf67-469f-b282-d08caf56beb4.png)
![Screenshot_20220315-134903](https://user-images.githubusercontent.com/364615/158440505-5f8ae9b7-020f-4696-80be-d4cb9630180e.png)
![Screenshot_20220315-134925](https://user-images.githubusercontent.com/364615/158440508-20c090d9-b717-46ff-90e2-cf1517ff05fd.png)

**Comment by clemens-tolboom** [comment]
Thanks for your answer ... lol ... discussed a long time ago :-p

I just clicked the ellipsis then __Copy Message Link__ https://discord.com/channels/684898665143206084/769285344809451572/935575448254054461

![image](https://user-images.githubusercontent.com/371014/158459947-80813275-b4c6-432b-b83a-070be5934e65.png)

I myself was wondering as Leaf stores files you could extract it to real FS then load it with dlopen, but have no experience with dlopen yet.

**Comment by mwcz** [comment]
Ah, I was on my phone and the copy link feature must not be possible on discord mobile.

What you suggest should work, it's just kind of a pain and introduces new error cases that have to be handled, like fs permission errors, no tmp dir available, no disk space, etc.  It's what I was getting at with this comment in the thread:

![Screenshot_20220316-093959](https://user-images.githubusercontent.com/364615/158603400-74fb0bed-79d9-4a4e-a1d2-321b396f8745.png)
